### ISSUE TITLE
SaveData.dat reset after modifying to enable theme-cache

### ISSUE THREAD

**Issue by yellows8** [yellows8/3ds_homemenu_extdatatool#1]
When SaveData.dat was modified to enable using the theme-cache, Home Menu resets SaveData.dat state so that no theme is used at all at certain times(listed below). It's unknown whether this can be fixed/worked-around.

This shouldn't be a problem if you just overwrite theme-cache with an actual DLC theme already installed+selected.
- Entering the shutdown screen
- Leaving Home Menu(including application launching)
- Sleep-mode
- Potentially other things

**Comment by lavanoid** [comment]
I have an idea, but I'm a complete noob when it comes to 3DS hacking. Anyway, when a custom SaveData.dat is written, would it be possible to tell the console that the theme name is that of a native one, such as "Simple Black" but still get it to read the cache?

I don't have any DLC's and I doubt I can buy any since Nintendo will want me to update my console first.

**Comment by profi200** [comment]
Home menu doesn't check if there is any DLC/build in theme for the cached theme installed but resets it for some reason sometimes.

The theme shop can be visited without updating.

**Comment by lavanoid** [comment]
@profi200 Yeah, the theme shop lets you browse it without updating but it won't let you download anything...

**Comment by profi200** [comment]
Did not know that. Just saw one can visit the theme shop on non-latest firmwares.

**Comment by yellows8** [comment]
"would it be possible to tell the console that the theme name is that of a native one, such as "Simple Black" but still get it to read the cache?" Obviously not, if you would actually read the wiki info: http://3dbrew.org/wiki/Home_Menu#SaveData.dat

**Comment by lavanoid** [comment]
Sorry, I didn't think of looking at that page - I was paying more attention to the page that explains the theme structure. Duurrp. Would have thought the maintainer would've put that info on the same page as the theme structure one.

On a side note (completely unrelated to themes), maybe it could be possible to exploit the 3DS through the Wi-Fi configuarion, seeing as it has higher privileges (I DO read the info placed on 3dbrew, and am grateful for the efforts.). Perhaps one could create an AP with a long string and cause the system to crash? I'm a noob so what do I know?

I assume you are the one who updates 3dbrew?

**Comment by yellows8** [comment]
I tried to look at the wifi code you're describing before(and even the wifi beacon handling code), but didn't find anything interesting really.

"I assume you are the one who updates 3dbrew?" One of those that does that, yes.

**Comment by lavanoid** [comment]
Oh, ok. Thanks anyway! May I ask how you analyze the 3DS firmware? I know neimod has a tool to decrypt it, but I've never actually seen it work. What parts of the firmware could you change? Is it possible to replace the certificates in the system then redirect traffic that is normally sent to Nintendo's servers to a local one? Maybe trick the console into downgrading, or even downloading a specific title (such as a theme)?

Sorry if I seem like I'm nagging you, it's just that as a programmer myself (a decent one - nowhere near as good as your expertise though) - I too get curious of how things work and try to figure them out... The 3DS is like a box of mysteries...

**Comment by yellows8** [comment]
Obviously we've been able to decrypt whatever 3DS titles we wanted (with private stuff) for a *long* time, there's public tools for doing that at this point as well.

Regarding the rest of your comment, it depends on the context. None of what you mentioned can be done from ninjhax on Old3DS(dunno what's the point in downgrading if you already have code exec).

**Comment by lavanoid** [comment]
Oh. The reason why I personally, would want to downgrade is because of user permissions. Code exec is great - don't get me wrong, but it also feels very limited too. It seems that Waffles Loader (or Gateway) on 4.5 gave much more flexibility over the system, such as adding homebrew to the home screen, NAND backup, and the list could go on forever.

I really like Ninjhax - I really appreciate everyone's efforts but we all know that we are being limited (only ARM11 exec :/ ). Other reasons why I would like to downgrade is because of system transfer, think about it - backup NAND and SD card, transfer content to another 3DS though System Transfer, then restore the backup.

I'd like to run homebrew on my 3DS but there's newer titles coming out that I won't be able to use because Nintendo demand that I update my system. If I had emunand - which isn't available in ninjhax - I'd be able to have homebrew and play newer games. Ninjhax gives you only two options - homebrew or games?

See what I mean? As for decrpting  the firmware - I really don't wan't to disassemble my console just for the sake of a NAND backup, as it's in near mint condition and I'd rather keep it that way.

**Comment by lavanoid** [comment]
What tools do you use? (If you don't mind me asking)

**Comment by yellows8** [comment]
If you mean for title decryption, learn2read "decrypt whatever 3DS titles we wanted (with private stuff)".

Either get a 3DS just for games, or wait for GW.

**Comment by lavanoid** [comment]
I do know how to read. I'm aware of the "private stuff", but you also said "public tools" - what tools??

**Comment by lavanoid** [comment]
Neither was I interested in "title decryption" - I was referring to the actual firmware.

**Comment by yellows8** [comment]
"firmware" = titles, see gbafail for said tools.

**Comment by lavanoid** [comment]
Ok. Wait, I'm aware that the system downloads the titles and installs them through system update (I've read a log that someone made when they monitored the traffic), but it's much of a surprise that things such as the BL and stuff would also be considered a 'title'. Well, I'll be...

One last question and I'll leave you alone - is it possible to get Pictochat back? I know you can load a DS firmware from a Flashcart but it always enters the DS setup, when ran on a 3DS.

Thanks in advance for your replies - despite them feeling a tad bit rude.

**Comment by yellows8** [comment]
"is it possible to get Pictochat back?" I dunno, maybe if you patch the binary, but I don't care about it either.

"despite them feeling a tad ..." Sorry, I'm kinda tired atm.

**Comment by lavanoid** [comment]
Ok, btw - I tried contacting Smealum and here's an idea for an exploit - Pokemon Bank. The concept can be similar to previous exploits, "carve" a custom save file and put it on a standard Pokemon Game Cart (i.e. Pokemon White 2), then when you launch Pokemon Bank and it reads the carts save data - an exploit is triggered. Just an idea though, not sure if its feasible.

Your not an easy person to contact - GitHub seems to be the only way of asking you stuff, other than that - it's like you don't exist. I guess you're the type of person who doesn't like to be nagged on the net; I understand. Your well known though.

Good luck with your future hacks and stuff!

**Comment by yellows8** [comment]
"Your not an easy person to contact" IRC, email, 3dbrew talk pages, and perhaps github.

Meh, I don't care for pokemon and I have my own private 3ds userland-process exploits already.

**Comment by lavanoid** [comment]
Well, I guess I don't look thorough enough -  suppose. Usually because I can't be bothered. Still though   - if anyone were to release a new exploit to the public; they could consider using Pokemon Bank as an entry point, also considering that it's a rather popular game.

Well, must be great being you, being able to do what you want with your console. ARP Spoofing would be pretty fun on a 3DS - dumping data to a .pcap and stuff. No one would suspect a thing... Surprised no one has made a file manager for ninjhax yet, would be interesting - even more interesting if we could browse the internal extdata too but...

**Comment by profi200** [comment]
There is nothing you could exploit in Pokemon Bank. It mostly don't use the save but uploads it to Nintendos servers. It uses only the Pokemon data and that is pretty secure.

Github is not the right place for such conversations. ---> #3dsdev on the EFnet

**Comment by lavanoid** [comment]
Well, I guess that makes sense. Meh, what's Nintendo gonna do really? Smea gave a lot of info about ssspwn but Nintendo couldn't do anything until it was released  - so who care's if they're reading this? It's not like we're sharing "bad" source code or anything. Just asking questions (consider me a consumer of exploits - what do I know? xD)

**Comment by yellows8** [comment]
Profi's point is, this is all offtopic for this github issue.

**Comment by lavanoid** [comment]
Ah, I see. Sorry - I guess my curiosity just got the better of me, mainy because I got Cubic Ninja today. Could just delete all the comments then.

**Comment by yellows8** [comment]
Fixed: 63e7d97946234b8e656a49aec0bf0add40162624

**Comment by yellows8** [comment]
In addition to the source code, see here regarding how the theme-DLC requirement was bypassed: http://3dbrew.org/wiki/Home_Menu#SaveData.dat

**Comment by ghost** [comment]
Oh great! Now I don't need to worry about a dumb DLC. Thank you!
